"""AArch64 lifting engine.

This engine turns one function's machine code into readable pseudo-C.  It is a
real (if pragmatic) decompiler for the code shapes generated by dex2c:

  * tracks a symbolic value for every register and for the interesting stack
    slots (the jvalue argument array and the stack canary slot),
  * resolves ADRP/ADR/literal loads into string constants and into
    JNIEnv vtable slots (JNI function pointers),
  * rewrites JNIEnv indirect calls into ``env->Method(args)`` calls,
  * detects the dex2c ``jvalue args[]`` pattern (``mov x3, sp`` + ``str`` to
    the frame) and emits a local ``jvalue`` array,
  * detects the stack canary (``mrs xN, tpidr_el0`` / ``ldr xN,[xN,#0x28]``)
    and emits the epilogue ``if (__stack_chk_guard != canary)`` check plus the
    ``__stack_chk_fail()`` cold block,
  * emits a return-value phi note when a join block can hold two different
    values for the ABI return register (e.g. ``0.0f`` from ``movi d8,0`` and
    the real result from ``fmov s8,s0``),
  * degrades gracefully: anything it cannot reason about is rendered as a
    literal ``// <insn>`` comment, so output is always honest.

Every *materialized* value becomes a named local (``v_class``, ``v_mid``,
``v_ret``...); pure register shuffling (``mov``/``fmov``/``movi`` of known
values) is folded away unless it crosses a join block.

The emitter produces lines in address order with labels/goto so that the
output mirrors the real control flow of the binaries this project targets.
"""

from __future__ import annotations

from ..disasm.engine import disassemble_detailed, Operand, CS_AC_READ, CS_AC_WRITE
from ..jni.analyzer import decode_mangled_suffix
from ..jni.sig import param_list, ret_type
from . import expr as E


class DecompFailure(Exception):
    pass


# C type of common JNI-result kinds
_RET_BY_METHOD = {
    "GetObjectClass": "jclass",
    "GetObjectArrayElement": "jobject",
    "GetFieldID": "jfieldID",
    "GetMethodID": "jmethodID",
    "CallVoidMethodA": "void",
    "CallObjectMethodA": "jobject",
    "CallBooleanMethodA": "jboolean",
    "CallByteMethodA": "jbyte",
    "CallCharMethodA": "jchar",
    "CallShortMethodA": "jshort",
    "CallIntMethodA": "jint",
    "CallLongMethodA": "jlong",
    "CallFloatMethodA": "jfloat",
    "CallDoubleMethodA": "jdouble",
    "NewStringUTF": "jstring",
    "NewString": "jstring",
    "NewByteArray": "jbyteArray",
    "NewIntArray": "jintArray",
    "NewObjectArray": "jobjectArray",
}

# result register that a JNI method returns into on AArch64
_FP_METHODS = {"CallFloatMethodA", "CallDoubleMethodA"}

# Fixed integer/pointer argument count for JNI methods (excluding env).
# dex2c always calls env->method(x0..x(n-1)); knowing the arity lets us
# stop rendering junk registers that hold leftover entry parameters.
_JNI_ARITY = {
    "GetVersion": 1, "DefineClass": 4, "FindClass": 2,
    "FromReflectedMethod": 2, "FromReflectedField": 2,
    "ToReflectedMethod": 2, "GetSuperclass": 2, "IsAssignableFrom": 3,
    "ToReflectedField": 2, "Throw": 2, "ThrowNew": 3,
    "ExceptionOccurred": 1, "ExceptionDescribe": 1, "ExceptionClear": 1,
    "FatalError": 2, "PushLocalFrame": 2, "PopLocalFrame": 2,
    "NewGlobalRef": 2, "DeleteGlobalRef": 2, "DeleteLocalRef": 2,
    "IsSameObject": 3, "NewLocalRef": 2, "EnsureLocalCapacity": 2,
    "AllocObject": 2, "NewObject": 3, "NewObjectV": 4, "NewObjectA": 4,
    "GetObjectClass": 2, "IsInstanceOf": 3, "GetMethodID": 4,
    "GetStaticMethodID": 4,
    "CallVoidMethodA": 4, "CallObjectMethodA": 4, "CallBooleanMethodA": 4,
    "CallByteMethodA": 4, "CallCharMethodA": 4, "CallShortMethodA": 4,
    "CallIntMethodA": 4, "CallLongMethodA": 4, "CallFloatMethodA": 4,
    "CallDoubleMethodA": 4,
    "GetFieldID": 4,
    "NewStringUTF": 2, "NewString": 2,
    "GetStringUTFLength": 2, "GetStringUTFChars": 3,
    "ReleaseStringUTFChars": 3, "GetStringLength": 2, "GetStringChars": 3,
    "ReleaseStringChars": 3,
    "GetArrayLength": 2,
    "NewObjectArray": 4, "GetObjectArrayElement": 3,
    "SetObjectArrayElement": 3,
    "NewBooleanArray": 2, "NewByteArray": 2, "NewCharArray": 2,
    "NewShortArray": 2, "NewIntArray": 2, "NewLongArray": 2,
    "NewFloatArray": 2, "NewDoubleArray": 2,
    "GetBooleanArrayElements": 4, "GetBooleanArrayRegion": 5,
    "SetBooleanArrayRegion": 5, "RegisterNatives": 4,
    "UnregisterNatives": 2, "MonitorEnter": 2, "MonitorExit": 2,
    "GetJavaVM": 2,
    "NewWeakGlobalRef": 2, "DeleteWeakGlobalRef": 2, "ExceptionCheck": 1,
    "NewDirectByteBuffer": 3, "GetDirectBufferAddress": 2,
    "GetDirectBufferCapacity": 2, "GetObjectRefType": 2,
}

_ARG_REGS = ("x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7")

# known fixed arity of libc/compiler-rt runtime calls this tool emits
_IMPORT_ARITY = {
    "__stack_chk_fail": 0,
    "__cxa_finalize": 1,
    "__cxa_atexit": 3,
}

_STORE_MNEM = ("str", "stur", "strb", "strh", "stp", "stnp")


def _is_store(m):
    return m in _STORE_MNEM


_DESC_RE = None  # set lazily


def _jvalue_field(typ: str) -> str:
    return {
        "jboolean": "z", "jbyte": "b", "jchar": "c", "jshort": "s",
        "jint": "i", "jlong": "j", "jfloat": "f", "jdouble": "d",
        "jobject": "l", "jstring": "l", "jarray": "l", "jclass": "l",
        "jmethodID": "j", "jfieldID": "j",
    }.get(typ, "")


class Lift:
    """Stateful linear-sweep lifter for one function body."""

    def __init__(self, elf, resolver, str_index):
        self.elf = elf
        self.resolver = resolver
        self.str_index = str_index or {}
        self.insns = []
        self.addr = 0
        self.size = 0
        self.name = ""

        self.regs = {}           # reg name -> Expr dict
        self.frame = 0           # prologue sub sp,sp,#frame
        self.x29_off = None      # x29 = sp + x29_off (frame-relative)
        self.tls_reg = None      # reg holding tpidr_el0 base
        self.canary_slot = None  # frame offset where guard is stored
        self.canary_var = None   # Expr name of the saved canary
        self.last_cmp = None     # (renderA, renderB) of top guard cmp
        self.ret_char = None     # descriptor return char for this function
        self.ret_reg = "x0"      # ABI return register name
        self.sig_desc = ""       # full recovered JNI descriptor

        # jvalue argument array bookkeeping
        self.args_base = None    # frame offset the args pointer points to
        self.args_stores = []    # [(index, expr, field)] pending
        self.args_flushed = False

        self.labels = set()      # branch target addresses
        self.phi = {}            # label addr -> set(render strings)
        self.lines = []
        self.prelude = []        # local declarations hoisted to the top
        self._declarations_emitted = set()
        self.var_counter = [0]
        self.param_exprs = {}    # reg name -> param Expr dict
        self._emitted = set()
        self._jni_used = set()
        self.entry_x0_env = False
        self.func_names = {}     # addr -> sub_XXXX map for known functions

    # ------------------------------------------------------------------ utils
    def _new_var(self, hint="v"):
        self.var_counter[0] += 1
        return f"{hint}_{self.var_counter[0]}"

    def _got(self, reg):
        return self.regs.get(reg)

    def _set(self, reg, e):
        if e is None:
            self.regs.pop(reg, None)
        else:
            self.regs[reg] = e

    def _emit_decls(self, decls):
        """Push local variable declarations into the function prelude.

        Declarations are emitted at most once (subsequent calls with the same
        text are harmless), so they are safe to insert speculatively from deep
        within the decoder.
        """
        for d in decls:
            if d not in self._declarations_emitted:
                self.prelude.append(f"    {d}")
                self._declarations_emitted.add(d)

    def _str_at(self, addr):
        if isinstance(addr, int):
            return self.str_index.get(addr)
        return None

    def _rd(self, insn):
        """Destination register (first write-only reg operand)."""
        for o in insn.operands:
            if o.kind == "reg" and o.is_write and not o.is_read:
                return o.reg
        # fallback: first reg operand
        for o in insn.operands:
            if o.kind == "reg":
                return o.reg
        return None

    def _writeregs(self, insn):
        out = []
        for o in insn.operands:
            if o.kind == "reg" and o.is_write:
                out.append(o.reg)
        if not out:
            for o in insn.operands:
                if o.kind == "reg":
                    out.append(o.reg)
        return out

    def _frame_off(self, base, disp):
        """Translate a memory operand base+disp to a frame-relative offset."""
        if base == "sp":
            return disp
        if base == "x29" and self.x29_off is not None:
            return self.x29_off + disp
        return None

    def _render(self, e):
        return E.render(e) if e is not None else "?"

    # ------------------------------------------------------------------ entry
    def decompile(self, addr, size, name="", jni_hint=None,
                  func_names=None, entry_env=None):
        self.insns = disassemble_detailed(self.elf, addr, size)
        if not self.insns:
            return []
        self.addr = addr
        self.size = size
        self.name = name
        if func_names:
            self.func_names.update(func_names)
        if entry_env is not None:
            self.entry_x0_env = entry_env

        self._collect_labels()
        self._init_entry_params(name or jni_hint)
        self._analyze_frame()

        for insn in self.insns:
            a = insn.address
            if a in self.labels and a not in self._emitted:
                self._emitted.add(a)
                self.lines.append(f"L_0x{a:x}:")
                # phi joins: fall-through into a block also merges values, so
                # combine branch-time candidates with the current register state
                cand = self._ret_candidates()
                if cand:
                    self.phi.setdefault(a, set()).update(cand)
                self._refresh_env_at_label()
                phis = self.phi.get(a)
                if phis and len(phis) > 1:
                    self.lines.append(
                        f"    // join: return value is one of "
                        f"{', '.join(sorted(phis))}")
            self._lift_insn(insn)
        return self.prelude + self.lines

    def _collect_labels(self):
        import struct
        from .aarch64util import decode_aarch64_insn
        labels = set()
        for insn in self.insns:
            if len(insn.bytes) < 4:
                continue
            word = int.from_bytes(insn.bytes[:4], "little")
            d = decode_aarch64_insn(word, insn.address)
            k = d.get("kind")
            tgt = d.get("target")
            if k in ("branch", "cond_branch") and isinstance(tgt, int):
                labels.add(tgt)
        self.labels = labels

    def _init_entry_params(self, name):
        """Bind JNI ABI entry registers (env, thiz, java params).

        For exported JNI methods x0 is the JNIEnv* and x1 the receiver; for
        internal (recovered, unnamed) functions the ABI registers are ordinary
        unknown parameters, so nothing gets bound and x0..x7 stay implicit.
        """
        self.params = _params_from_name(name)
        if self.entry_x0_env:
            self._set("x0", E.env())
            self._set("w0", E.env())
            self._set("x1", E.param(1, "thiz"))
            self._set("w1", E.param(1, "thiz"))
            gp = 2        # next general-purpose arg register (x2..)
            fp = 0        # next floating-point arg register (s0..)
            for i, (typ, n) in enumerate(self.params):
                if typ in ("jfloat", "jdouble"):
                    sreg = f"s{fp}"
                    dreg = f"d{fp}"
                    fp += 1
                    self._set(sreg, E.param(i, n))
                    self._set(dreg, E.param(i, n))
                else:
                    self._set(f"x{gp}", E.param(i, n))
                    self._set(f"w{gp}", E.param(i, n))
                    gp += 1
            return

        # internal function: keep the ABI argument registers implicit (do not
        # invent names); any register that reaches output is rendered by its
        # real AArch64 name, which is the honest notation for a function whose
        # calling convention is unknown.
        return

    def _analyze_frame(self):
        import itertools
        frame = 0
        for insn in self.insns:
            m = insn.mnemonic
            ops = insn.operands
            if m == "sub" and len(ops) >= 3 and ops[0].kind == "reg" \
               and ops[0].reg == "sp" and ops[1].reg == "sp" \
               and ops[2].kind == "imm":
                frame = ops[2].imm
                break
        self.frame = frame
        # x29 offset
        for insn in self.insns:
            m = insn.mnemonic
            ops = insn.operands
            if m == "add" and len(ops) >= 3 and ops[0].kind == "reg" \
               and ops[0].reg in ("x29", "fp") and ops[1].kind == "reg" \
               and ops[1].reg == "sp" and ops[2].kind == "imm":
                self.x29_off = ops[2].imm
                break
            if m == "mov" and len(ops) == 2 and ops[0].reg in ("x29", "fp") \
               and ops[1].reg == "sp":
                self.x29_off = 0
                break
        if self.x29_off is None:
            self.x29_off = 0

    # ================================================================ lifters
    def _lift_insn(self, insn):
        m = insn.mnemonic
        a = insn.address

        if m == "sub" and len(insn.operands) >= 3 and \
           insn.operands[0].kind == "reg" and insn.operands[0].reg == "sp" \
           and insn.operands[1].reg == "sp":
            return  # prologue
        if m in ("nop",):
            return
        if m == "mrs":
            self._lift_mrs(insn)
            return
        if m in ("ldr", "ldur", "ldp", "ldnp", "ldrsw", "ldrb", "ldrh",
                 "prfm", "str", "stur", "stp", "stnp", "strb", "strh"):
            self._lift_ld_st(insn)
            return
        if m == "ret":
            self._lift_ret(insn)
            return
        if m in ("add", "adr", "adrp", "mov", "movz", "movn", "movk", "orr",
                 "and", "eor", "lsl", "lsr", "asr", "mul", "madd", "msub",
                 "neg", "sxtb", "sxth", "sxtw", "uxtb", "uxth", "uxtw"):
            self._lift_arith(insn)
            return
        if m == "bl":
            self._lift_bl(insn)
            return
        if m == "br":
            self._lift_br(insn, tail=True)
            return
        if m == "blr":
            self._lift_br(insn, tail=False)
            return
        if m == "b":
            self._lift_b(insn)
            return
        if m.startswith("b.") or m in ("cbz", "cbnz", "tbz", "tbnz"):
            self._lift_cond(insn)
            return
        if m in ("cmp", "cmn", "tst", "subs", "ands", "adds", "bics"):
            self._lift_cmp(insn)
            return
        if m in ("fmov", "movi", "fmov") or m.startswith("f"):
            self._lift_fp(insn)
            return
        if m in ("csel", "cset", "csinc", "csinv", "csneg", "cinc", "cinv",
                 "cneg"):
            self._lift_select(insn)
            return
        if m in ("ccmp", "ccmn"):
            self.lines.append(f"    // {insn.text}  ; conditional flags set")
            return
        self.lines.append(f"    // {insn.text}")

    # ------------------------------------------------------------------ mrs
    def _lift_mrs(self, insn):
        ops = insn.operands
        rd = self._rd(insn)
        if rd and "tpidr_el0" in insn.op_str:
            self.tls_reg = rd
            self.lines.append(f"    // {rd} = __builtin_thread_pointer()  "
                              f"(tpidr_el0)")
        else:
            self.lines.append(f"    // {insn.text}")

    # ------------------------------------------------------------------ fp
    def _lift_fp(self, insn):
        m = insn.mnemonic
        ops = insn.operands
        if m == "fmov" and len(ops) == 2 and ops[0].kind == "reg" \
           and ops[1].kind == "reg":
            src = self._got(ops[1].reg)
            self._set(ops[0].reg, src)
            # dN and sN alias: an 8-byte move affects both views
            if ops[0].reg.startswith("d") and src is not None:
                self._set(ops[0].reg[:-1] + "s" + ops[0].reg[1:], src)
            if ops[0].reg.startswith("s") and src is not None:
                self._set(ops[0].reg[:-1] + "d" + ops[0].reg[1:], src)
            return
        if m == "movi" and len(ops) >= 2 and ops[0].kind == "reg":
            # movi d8, #0  -> s8 = d8 = 0.0  (fp zero used in phi join)
            val = 0.0
            for o in ops[1:]:
                if o.kind == "imm":
                    val = float(o.imm)
                    break
            self._set(ops[0].reg, E.fimm(val))
            if ops[0].reg.startswith("d"):
                self._set(ops[0].reg[:-1] + "s" + ops[0].reg[1:], E.fimm(val))
            return
        self.lines.append(f"    // {insn.text}")

    # ------------------------------------------------------------------ arith
    def _lift_arith(self, insn):
        m = insn.mnemonic
        ops = insn.operands
        rd = self._rd(insn)

        if m == "adrp":
            tgt = _insn_target(insn, ops)
            if tgt is not None:
                self._set(rd, E.addr_of(E.imm(tgt)))
                s = self._str_at(tgt)
                if s:
                    self._set(rd, E.string(s, tgt))
            else:
                self._set(rd, E.reg(rd))
            return

        if m == "adr":
            tgt = _insn_target(insn, ops)
            if tgt is not None:
                s = self._str_at(tgt)
                if s:
                    self._set(rd, E.string(s, tgt))
                else:
                    self._set(rd, E.addr_of(E.imm(tgt)))
            return

        if m == "mov" and len(ops) == 2 and ops[0].kind == "reg" \
           and ops[1].kind == "reg":
            if ops[1].reg == "sp":
                # x3 = sp   (jvalue args base at frame+0)
                if ops[0].reg in ("x3", "w3"):
                    self.args_base = 0
                    self.args_stores = []
                    self.args_flushed = False
                    self._set("x3", {"k": "argsptr", "b": 0})
                    self._set("w3", {"k": "argsptr", "b": 0})
                else:
                    self._set(ops[0].reg, E.reg("sp"))
                return
            src = self._got(ops[1].reg)
            if ops[1].reg in ("xzr", "wzr"):
                src = E.imm(0)
                self._set(ops[0].reg, src)
            else:
                self._set(ops[0].reg, src)
            return

        if m in ("movz", "movn", "movk") and len(ops) >= 2 \
           and ops[0].kind == "reg" and ops[1].kind == "imm":
            v = ops[1].imm & 0xFFFF
            lane = 0
            if len(ops) >= 3 and ops[2].kind == "imm":
                lane = ops[2].imm
            mask = 0xFFFFFFFF if ops[0].reg.startswith("w") else \
                0xFFFFFFFFFFFFFFFF
            if m == "movk":
                # lanes accumulate: movk merges into the previously built value
                cur = self._got(ops[0].reg)
                basev = 0
                if E.kind_of(cur) == "imm":
                    basev = cur["v"]
                merged = (basev & ~(0xFFFF << lane)) | (v << lane)
                self._set(ops[0].reg, E.imm(merged & mask))
                return
            if m == "movn":
                full = (~(ops[1].imm << lane)) & mask
            elif m == "movz":
                full = (ops[1].imm << lane) & mask
            self._set(ops[0].reg, E.imm(full))
            return

        if m == "add" and len(ops) == 3 and ops[0].kind == "reg" \
           and ops[1].kind == "reg" and ops[2].kind == "imm":
            # x29, sp, #u  (frame pointer setup)
            if ops[0].reg == "x29" and ops[1].reg == "sp":
                self.x29_off = ops[2].imm
                return
            # x3, sp, #8   (jvalue args base)
            base = self._got(ops[1].reg)
            if ops[0].reg == "x3" and ops[1].reg == "sp":
                self.args_base = ops[2].imm
                self.args_stores = []
                self.args_flushed = False
                self._set("x3", {"k": "argsptr", "b": self.args_base})
                self._set("w3", {"k": "argsptr", "b": self.args_base})
                return
            if E.kind_of(base) == "addr":
                total = base["v"]["v"] + ops[2].imm if \
                    isinstance(base.get("v"), dict) and \
                    base["v"].get("k") == "imm" else ops[2].imm
                s = self._str_at(total)
                if s:
                    self._set(ops[0].reg, E.string(s, total))
                    return
                self._set(ops[0].reg, E.addr_of(E.imm(total)))
                return
            if E.kind_of(base) in ("imm",):
                total = base["v"] + ops[2].imm
                self._set(ops[0].reg, E.imm(total))
                return
            # fallthrough: register addition
            self._set(ops[0].reg, E.binop("+", E.reg(ops[1].reg),
                                          E.imm(ops[2].imm)))
            return

        if m in ("orr", "and", "eor", "lsl", "lsr", "asr") and \
           len(ops) == 3 and ops[0].kind == "reg" and ops[1].kind == "reg":
            op = {"orr": "|", "and": "&", "eor": "^", "lsl": "<<",
                  "lsr": ">>", "asr": ">>"}[m]
            rhs = E.imm(ops[2].imm) if ops[2].kind == "imm" else \
                E.reg(ops[2].reg)
            self._set(ops[0].reg, E.binop(op, E.reg(ops[1].reg), rhs))
            return

        # anything else: best-effort register assignment
        if rd and m in ("sxtb", "sxth", "sxtw", "uxtb", "uxth", "uxtw"):
            src = self._got(ops[1].reg) if len(ops) > 1 else None
            self._set(rd, src)
            return
        self.lines.append(f"    // {insn.text}")

    # ------------------------------------------------------------------ mem
    def _lift_ld_st(self, insn):
        m = insn.mnemonic
        ops = insn.operands
        a = insn.address

        # literal loads: ldr xN, <literal target>
        if m in ("ldr", "ldur") and ops and ops[0].kind == "reg" and \
           len(ops) == 1:
            return self._lift_ldr_literal(insn)

        mem = _mem_op(insn)
        if mem is None:
            self.lines.append(f"    // {insn.text}")
            return
        base, disp, acc = mem
        store = _is_store(m)
        pair = m in ("stp", "stnp", "ldp", "ldnp")
        regs = []
        for o in ops:
            if o.kind == "reg" and len(regs) < (2 if pair else 1):
                regs.append(o.reg)

        # vector reg access is a spill/restore; keep a comment only for stores
        if store and base not in ("sp", "x29"):
            self.lines.append(f"    // {insn.text}")
            return

        # ---- canary guard load: ldr xR, [tlsreg, #0x28]
        if base == self.tls_reg and disp == 0x28 and not store:
            self._set(_first_reg(ops), E.sym("__stack_chk_guard"))
            return

        fo = self._frame_off(base, disp)

        # ---- store into the jvalue args region (single + pair stores)
        if store and self.args_base is not None and \
                fo is not None and fo >= self.args_base:
            for i, r in enumerate(regs[:2]):
                self._lift_arg_store_idx(insn, fo + i * 8, r)
            return

        # ---- canary save slot (single store of the guard value)
        if store and fo is not None and not pair:
            val = self._got(_first_reg(ops)) if _first_reg(ops) else None
            if E.kind_of(val) == "sym" and val.get("v") == "__stack_chk_guard":
                self.canary_slot = fo
                self.canary_var = "canary"
                self._emit_decls({"uintptr_t canary;",
                                  "extern uintptr_t __stack_chk_guard;"})
                self.lines.append(f"    // guard saved at frame+0x{fo:x}")
                return

        # ---- canary load back
        if not store and fo is not None:
            if fo == self.canary_slot:
                self._set(_first_reg(ops), E.var("canary"))
                return

        # ---- JNIEnv vtable: [env] and [env->functions, #off]
        # env itself may live in any register x0/x19/x20... (dex2c keeps a
        # callee-saved alias), so match on the *expression*, not the name.
        val = self._got(base)
        if E.kind_of(val) == "env":
            if disp == 0:
                self._set(_first_reg(ops), E.envfn())
                return
        if E.kind_of(val) == "envfn":
            from ..jni.analyzer import jni_index_from_offset
            name = jni_index_from_offset(disp)
            if name:
                self._set(_first_reg(ops), E.jnifn(disp // 8, name))
                return
            self._set(_first_reg(ops), E.envfn())
            return

        # ---- [xN,#disp] loads where xN holds a resolved address / constant
        if not store:
            src = self._got(base)
            total = None
            if E.kind_of(src) == "addr" and isinstance(src.get("v"), dict) \
                    and src["v"].get("k") == "imm":
                total = src["v"]["v"] + disp
            elif E.kind_of(src) == "imm":
                total = src["v"] + disp
            if total is not None:
                if pair:
                    pass
                s = self._str_at(total)
                if s:
                    self._set(_first_reg(ops), E.string(s, total))
                    return
                g = self.resolver.got_name(total)
                if g:
                    self._set(_first_reg(ops), E.sym(g))
                    return
                self._set(_first_reg(ops), E.mem(None, total, 8))
                return

        # ---- plain frame-relative store: keep an honest comment
        if store:
            self.lines.append(f"    // {insn.text}")
            return

        # ---- pair loads: restore both registers from memory
        if pair:
            for i, r in enumerate(regs[:2]):
                off = disp + i * 8
                self._set(r, E.mem(E.reg(base), off, 8))
            return

        # ---- plain [xN,#disp] load of an untracked base
        self._set(_first_reg(ops), E.mem(E.reg(base), disp, 8))
        return

    def _lift_ldr_literal(self, insn):
        t = _insn_target(insn, insn.operands)
        rd = self._rd(insn)
        if t is None:
            self.lines.append(f"    // {insn.text}")
            return
        s = self._str_at(t)
        if s:
            self._set(rd, E.string(s, t))
            return
        # maybe a pointer to an import (GOT-free PREL31 style)
        pt = self.elf.addr_to_file(t)
        if pt is not None:
            raw = self.elf.bytes_at(pt, 8)
            if raw and len(raw) == 8:
                import struct
                ptr = struct.unpack("<Q", raw)[0]
                nm = self.resolver.resolve(ptr)
                if nm:
                    self._set(rd, E.sym(nm))
                    return
        self._set(rd, E.addr_of(E.imm(t)))

    def _lift_arg_store_idx(self, insn, fo, reg):
        val = self._got(reg)
        if val is None:
            val = E.reg(reg)
        idx = (fo - self.args_base) // 8
        # field by param type if known
        field = ""
        if E.kind_of(val) == "param" and self.params and \
                E.value_of(val) < len(self.params):
            field = _jvalue_field(self.params[E.value_of(val)][0] if
                                  self.params else "")
        if not field:
            field = _store_field(insn)
        self.args_stores.append((idx, val, field))
        self._set(reg, val)

    # ------------------------------------------------------------------ calls
    def _lift_bl(self, insn):
        tgt = _insn_target(insn, insn.operands)
        if tgt is not None:
            nm = self.resolver.resolve(tgt)
            if nm is None and self.func_names:
                nm = self.func_names.get(tgt)
            if nm:
                self.lines.append(f"    {nm}();")
            else:
                self.lines.append(f"    // bl 0x{tgt:x}")
        else:
            self.lines.append(f"    // {insn.text}")
        self._clobber_caller_saved()

    def _lift_br(self, insn, tail=False):
        ops = insn.operands
        fnreg = _first_reg(ops)
        val = self._got(fnreg)
        if E.kind_of(val) != "jnifn":
            self.lines.append(f"    // {insn.text} (indirect)")
            self._clobber_caller_saved()
            return
        name = val["n"]
        args = self._collect_jni_args(fnreg)
        argtext = ", ".join(args)
        cty = _RET_BY_METHOD.get(name, "void")
        is_void = cty == "void"

        self._maybe_recover_sig(name, args)

        # flush a pending jvalue array before the call
        pre = []
        if self.args_stores:
            n = max(i for i, _, _ in self.args_stores) + 1
            pre.append(f"    jvalue args[{n}];")
            for i, e, fld in sorted(self.args_stores):
                if fld:
                    pre.append(f"    args[{i}].{fld} = {self._render(e)};")
                else:
                    pre.append(f"    args[{i}] = {self._render(e)};")
            self.args_stores = []
            self.args_flushed = True

        calltext = f"env->{name}({argtext})"
        self._clobber_caller_saved()

        if tail:
            # indirect tail call: the result *is* the function return value
            self.lines.extend(pre)
            self.lines.append(f"    return {calltext};")
            self._jni_used.add(name)
            self.args_base = None
            return

        self.lines.extend(pre)
        if is_void:
            self.lines.append(f"    {calltext};")
            self._jni_used.add(name)
        else:
            hint = self._result_hint(name)
            vname = self._new_var(hint)
            self.lines.append(f"    {cty} {vname} = {calltext};")
            # bind ABI result register *after* the clobber so it survives
            if name in _FP_METHODS:
                self._set("s0", E.var(vname))
                self._set("d0", E.var(vname))
                self._set("s8", E.var(vname))
                self._set("d8", E.var(vname))
            else:
                self._set("x0", E.var(vname))
                self._set("w0", E.var(vname))
            self._result_var = E.var(vname)
            self._jni_used.add(name)
        self.args_base = None

    def _collect_jni_args(self, fnreg):
        """Render x0..x(n-1) as the JNI call arguments (fnreg excluded).

        arg[0] is always `env` for a JNIEnv vtable call; the remaining slots
        come from the tracked register values.  Registers whose meaning fell
        out of the light liveness model render as traced comments.
        """
        name = self._got(fnreg).get("n") if self._got(fnreg) is not None \
            else None
        arity = _JNI_ARITY.get(name or "", len(_ARG_REGS))
        args = []
        for i, regn in enumerate(_ARG_REGS[:arity]):
            if regn == fnreg:
                continue
            if i == 0:
                args.append("env")
                continue
            e = self._got(regn)
            if e is None:
                args.append(regn)  # honest: the register name
                continue
            if E.kind_of(e) == "argsptr":
                args.append("args" if self.args_stores or self.args_flushed
                            else "NULL")
                continue
            r = self._render(e)
            if r in ("?", "/* ??? */"):
                args.append(regn)
                continue
            if r == "0":
                r = "NULL"
            args.append(r)
        return args

    def _maybe_recover_sig(self, name, args):
        """If this is a GetMethodID call, recover the JNI descriptor from the
        string args and use it to pick the ABI return register."""
        if name != "GetMethodID" or len(args) < 4:
            return
        desc = args[3].strip('"')
        import re
        m = re.match(r"^\((.*)\)([A-Z])$", desc)
        if not m:
            return
        self.sig_desc = desc
        self.ret_char = m.group(2)
        if self.ret_char in ("F", "D"):
            self.ret_reg = "s0"
        elif self.ret_char == "V":
            self.ret_reg = None
        else:
            self.ret_reg = "x0"

    def _result_hint(self, name):
        return {
            "GetObjectClass": "v_class",
            "GetObjectArrayElement": "v_elem",
            "GetMethodID": "v_mid",
            "GetFieldID": "v_fid",
            "NewStringUTF": "v_str",
            "NewString": "v_str",
        }.get(name, "v_ret")

    # ------------------------------------------------------------------ branch
    def _lift_b(self, insn):
        tgt = _insn_target(insn, insn.operands)
        if tgt is None:
            self.lines.append(f"    // {insn.text}")
            return
        imp = self.resolver.resolve(tgt) if self.resolver.inside_plt(tgt) \
            else None
        if imp is not None:
            args = self._collect_import_args(tgt, imp)
            if args is not None:
                self.lines.append(
                    f"    {imp}({', '.join(args)});   // tail call "
                    f"(no return to caller)")
            else:
                self.lines.append(
                    f"    // tail call -> {imp}()   ; argument registers "
                    f"not resolved")
            return
        if self.func_names and tgt in self.func_names and tgt != self.addr:
            nm = self.func_names[tgt]
            self.lines.append(f"    {nm}();   // tail call")
            return
        # an unconditional fast-path jump inside the function (loops /
        # join blocks) still needs the target label.
        self.lines.append(f"    goto L_0x{tgt:x};")

    def _collect_import_args(self, tgt, name):
        """Render the argument registers for a tail call to an import, if all
        of its (known) arguments are still tracked."""
        arity = _IMPORT_ARITY.get(name)
        if arity is None:
            return None
        args = []
        for i in range(arity):
            e = self._got(f"x{i}")
            if e is None:
                return None
            r = self._render(e)
            if r in ("?", "/* ??? */"):
                return None
            args.append(r)
        return args

    def _lift_cond(self, insn):
        m = insn.mnemonic
        ops = insn.operands
        tgt = _insn_target(insn, ops)
        if tgt is None:
            self.lines.append(f"    // {insn.text}")
            return

        if m in ("cbz", "cbnz"):
            regn = _first_reg(ops)
            val = self._got(regn)
            r = self._render(val)
            if r in ("?", "/* ??? */"):
                r = regn
            self._record_phi(tgt, edge_zero=(m == "cbz"))
            cond = f"!{r}" if m == "cbz" else f"{r} != 0"
            self.lines.append(f"    if ({cond}) goto L_0x{tgt:x};")
            return

        if m.startswith("b."):
            suffix = m[2:]
            cmp = self.last_cmp
            self.last_cmp = None  # flags are consumed by a conditional branch
            # canary failure: (__stack_chk_guard != canary)
            if cmp and suffix == "ne" and self._is_canary_cmp(cmp):
                self.lines.append(
                    f"    if (__stack_chk_guard != {cmp[1]}) "
                    f"goto L_0x{tgt:x};   // stack smashing")
                return
            if cmp and suffix == "eq" and self._is_canary_cmp(cmp):
                self.lines.append(
                    f"    if (__stack_chk_guard == {cmp[1]}) "
                    f"goto L_0x{tgt:x};")
                return
            self._record_phi(tgt)
            if cmp is not None and isinstance(cmp, tuple) and len(cmp) == 2 \
                    and cmp[0] != "__stack_chk_guard":
                op = _cond_operator(suffix)
                if op is not None and cmp[1] not in ("?", "/* ??? */"):
                    self.lines.append(
                        f"    if ({cmp[0]} {op} {cmp[1]}) goto L_0x{tgt:x};")
                    return
            ref = _aarch64_simple_cond(suffix)
            if ref is None:
                self.lines.append(f"    // {insn.text}")
                return
            self.lines.append(f"    if {ref} goto L_0x{tgt:x};")
            return

        if m in ("tbz", "tbnz"):
            regn = _first_reg(ops)
            bit = None
            for o in ops[1:]:
                if o.kind == "imm":
                    bit = o.imm
                    break
            r = self._render(self._got(regn))
            self._record_phi(tgt)
            if bit is not None:
                op = "!=" if m == "tbnz" else "=="
                self.lines.append(
                    f"    if (({r} >> {bit} & 1) {op} 0) "
                    f"goto L_0x{tgt:x};")
            else:
                self.lines.append(f"    // {insn.text}")

    def _refresh_env_at_label(self):
        """Recover env into x0 at a join block.

        dex2c failure blocks sometimes do ``mov x0, xzr; ret`` before a later
        branch label that re-enters code which still needs ``env`` in x0 (a
        tail-call block).  On the failing edge x0 genuinely holds 0, but on the
        edge reaching the label from the top it is still env.  When x0 holds a
        constant 0 at a label and no callee-saved register is keeping env alive
        any more, restore the entry binding — the only sane value the alias
        could have here.
        """
        x0 = self._got("x0")
        if not (E.kind_of(x0) == "imm" and x0["v"] == 0):
            return
        for k, e in self.regs.items():
            if k.startswith("x") and E.kind_of(e) == "env":
                try:
                    if int(k[1:]) >= 19:
                        return
                except ValueError:
                    pass
        if self.entry_x0_env:
            self._set("x0", E.env())
            self._set("w0", E.env())

    def _record_phi(self, tgt, edge_zero=False):
        if edge_zero:
            # the taken edge of a cbz/beq carries a zero return value
            val = "0.0f" if self.ret_char in ("F", "D") else "0"
            self.phi.setdefault(tgt, set()).add(val)
            return
        cand = self._ret_candidates()
        if cand:
            self.phi.setdefault(tgt, set()).update(cand)

    def _ret_candidates(self):
        """Render the plausible return-register values currently in flight."""
        vals = set()
        for regn in (self.ret_reg, "s8", "d8", "s0", "d0", "x0", "w0"):
            e = self._got(regn)
            if e is None:
                continue
            k = E.kind_of(e)
            if k in ("var", "fimm", "str"):
                vals.add(self._render(e))
            elif k == "imm" and e["v"] == 0:
                vals.add("0")
        return vals

    def _is_canary_cmp(self, cmp):
        lhs, rhs = cmp
        return lhs == "__stack_chk_guard" and rhs == "canary"

    # ------------------------------------------------------------------ select
    def _lift_select(self, insn):
        m = insn.mnemonic
        ops = insn.operands
        rd = self._rd(insn)
        if rd is None:
            self.lines.append(f"    // {insn.text}")
            return
        # capstone folds the condition into op_str instead of an operand
        cond = "al"
        parts = insn.op_str.split(",")
        if len(parts) >= 2 and parts[-1].strip().lower() in (
                "eq", "ne", "cs", "hs", "cc", "lo", "mi", "pl", "vs", "vc",
                "hi", "ls", "ge", "lt", "gt", "le", "al"):
            cond = parts[-1].strip().lower()
        cond_txt = self._cond_text(cond)

        rn = None
        rm = None
        if m in ("csel", "csinc", "csinv", "csneg") and len(ops) >= 3:
            rn = self._got(ops[1].reg) if ops[1].kind == "reg" else None
            rm = self._got(ops[2].reg) if ops[2].kind == "reg" else None
        elif m in ("cinc", "cinv", "cneg", "cset") and len(ops) >= 1:
            pass
        if rn is None and len(ops) >= 2 and ops[1].kind == "reg":
            rn = self._got(ops[1].reg)

        rn_t = self._render(rn) if rn is not None else "0"
        rm_t = self._render(rm) if rm is not None else "0"

        if m == "csel":
            self.lines.append(f"    {rd} = {cond_txt} ? {rn_t} : {rm_t};")
            return
        if m == "cset":
            self.lines.append(f"    {rd} = {cond_txt} ? 1 : 0;")
            return
        if m == "cinc":
            self.lines.append(f"    {rd} = {cond_txt} ? {rn_t} + 1 : {rn_t};")
            return
        if m == "cinv":
            self.lines.append(f"    {rd} = {cond_txt} ? ~({rn_t}) : {rn_t};")
            return
        if m == "cneg":
            self.lines.append(f"    {rd} = {cond_txt} ? -({rn_t}) : {rn_t};")
            return
        if m in ("csinc", "csinv", "csneg"):
            op = {"csinc": "+1", "csinv": "~", "csneg": "-"}.get(m, "+1")
            self.lines.append(f"    {rd} = {cond_txt} ? {rn_t} : "
                              f"{op}({rm_t});")
            return
        self.lines.append(f"    // {insn.text}")

    def _cond_text(self, suffix):
        """Render a condition for the current flags state.

        If a tracked ``cmp`` is pending, produce a real C comparison; otherwise
        fall back to an honest ``(flags XX)`` placeholder (the flags are real,
        the operands simply were not worth tracking).
        """
        cmp = self.last_cmp
        if cmp is not None and isinstance(cmp, tuple) and len(cmp) == 2:
            lhs, rhs = cmp
            op = _cond_operator(suffix)
            if op and lhs != "__stack_chk_guard":
                return f"({lhs} {op} {rhs})"
        return f"(flags {suffix.upper()})"

    # ------------------------------------------------------------------ cmp
    def _lift_cmp(self, insn):
        ops = insn.operands
        lhs = rhs = None
        if ops and ops[0].kind == "reg":
            lhs = self._got(ops[0].reg)
            lhs_t = self._render(lhs)
            if lhs_t in ("?", "/* ??? */"):
                lhs_t = ops[0].reg
            if len(ops) > 1:
                o2 = ops[1]
                if o2.kind == "reg":
                    rhs = self._got(o2.reg)
                    rhs_t = self._render(rhs)
                    if rhs_t in ("?", "/* ??? */"):
                        rhs_t = o2.reg
                elif o2.kind == "imm":
                    v = o2.imm
                    rhs_t = f"0x{v:x}" if v > 0x7FFFFFFF else str(v)
                    rhs = E.imm(v)
            else:
                rhs_t = "0"
            # stack-canary guard compare (used by _lift_cond for b.ne/b.eq)
            if E.kind_of(lhs) == "sym" and lhs.get("v") == "__stack_chk_guard":
                self.last_cmp = ("__stack_chk_guard", rhs_t)
                return
            if E.kind_of(rhs) == "sym" and rhs.get("v") == "__stack_chk_guard":
                self.last_cmp = ("__stack_chk_guard", lhs_t)
                return
            if lhs_t is not None and rhs_t is not None:
                self.last_cmp = (lhs_t, rhs_t)
                if insn.mnemonic in ("cmp", "cmn"):
                    return
        self.last_cmp = None
        self.lines.append(f"    // {insn.text}  ; flags set")

    # ------------------------------------------------------------------ ret
    def _lift_ret(self, insn):
        if self.ret_char == "V":
            self.lines.append("    return;")
            return
        e = self._got(self.ret_reg or "x0")
        if e is None:
            e = self._got("w0")
        if e is None:
            # callee-saved return var still live (e.g. s8 for float results)
            for cand in ("s8", "d8", "s0", "d0", "x0", "w0"):
                ce = self._got(cand)
                if ce is not None:
                    e = ce
                    break
        if e is None:
            self.lines.append("    return;")
            return
        r = self._render(e)
        if r in ("?", "/* ??? */", "NULL", "0"):
            if self.ret_char in ("F", "D"):
                r = "0.0f"
            elif r in ("?", "/* ??? */"):
                r = self.ret_reg or "x0"
        phinote = ""
        if self.ret_char in ("F", "D") and self.canary_slot is not None:
            phinote = "   // phi: 0.0f or float result"
        self.lines.append(f"    return {r};{phinote}")

    # ------------------------------------------------------------------ misc
    def _clobber_caller_saved(self):
        for k in list(self.regs):
            if k.startswith("x") or k.startswith("w"):
                try:
                    n = int(k[1:])
                except ValueError:
                    continue
                if n <= 18:
                    self.regs.pop(k, None)
            elif k.startswith("s") or k.startswith("d") or k.startswith("v"):
                try:
                    n = int(k[1:])
                except ValueError:
                    continue
                if n <= 18:
                    self.regs.pop(k, None)


def _params_from_name(name):
    """Parse a (possibly d2c-mangled) JNI export name into [(type, name)]."""
    if not name or "__" not in name:
        return []
    _, suffix = name.split("__", 1)
    desc = decode_mangled_suffix(suffix)
    if not desc.startswith("("):
        # decode_mangled_suffix returns the params part sans parens
        return param_list(f"({desc});".replace("));", ");")) \
            if ";" not in desc else param_list(f"({desc})")
    return param_list(desc)


def _insn_target(insn, ops):
    """Resolve branch/PC-relative target from operands or the raw word."""
    from .aarch64util import decode_aarch64_insn
    for o in ops:
        if o.kind == "imm":
            # For branch instructions capstone exposes the absolute target.
            return o.imm
    if len(insn.bytes) >= 4:
        word = int.from_bytes(insn.bytes[:4], "little")
        d = decode_aarch64_insn(word, insn.address)
        t = d.get("target")
        if isinstance(t, int):
            return t
    return None


def _mem_op(insn):
    for o in insn.operands:
        if o.kind == "mem":
            base = o.mem_base
            if base == "fp":  # capstone aliases x29 as "fp" in mem bases
                base = "x29"
            return (base, o.mem_disp, o.access)
    return None


def _first_reg(ops):
    for o in ops:
        if o.kind == "reg":
            return o.reg
    return None


def _store_field(insn):
    """jvalue union field for a raw store, guessed from the register width."""
    reg = _first_reg(insn.operands)
    if not reg:
        return ""
    if reg.startswith("w"):
        return "i"
    if reg.startswith(("s", "d")):
        return "f" if reg.startswith("s") else "d"
    if reg.startswith("q"):
        return ""
    return "l"


def _aarch64_simple_cond(suffix):
    return {
        "eq": "(flags EQ)",
        "ne": "(flags NE)",
        "cs": "(flags CS)", "hs": "(flags CS)",
        "cc": "(flags CC)", "lo": "(flags CC)",
        "mi": "(flags MI)", "pl": "(flags PL)",
        "vs": "(flags VS)", "vc": "(flags VC)",
        "hi": "(flags HI)", "ls": "(flags LS)",
        "ge": "(flags GE)", "lt": "(flags LT)",
        "gt": "(flags GT)", "le": "(flags LE)",
    }.get(suffix)


def _cond_operator(suffix):
    """C comparison operator for a branch/select condition when the operands
    of the preceding cmp/cmn are known."""
    return {
        "eq": "==", "ne": "!=",
        "lt": "<", "le": "<=", "gt": ">", "ge": ">=",
        "lo": "<", "ls": "<=", "hi": ">", "hs": ">=", "cs": ">=",
        "cc": "<",
    }.get(suffix)


def decompile_aarch64(elf, resolver, str_index, addr, size, name="",
                      jni_hint=None, func_names=None, entry_env=None):
    return Lift(elf, resolver, str_index).decompile(
        addr, size, name, jni_hint, func_names=func_names,
        entry_env=entry_env)