"""Reports and output rendering."""

from __future__ import annotations

import os
import json


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)
    return path


def render_c_header(elf, sec, arch, soname, build_id, sha256_hex=None):
    lines = []
    lines.append("/*")
    lines.append(" * SO2C - Android shared object analysis/decompilation.")
    lines.append(" *")
    lines.append(f" * Library : {soname or 'unknown'}")
    lines.append(f" * Arch    : {arch}")
    if build_id:
        lines.append(f" * BuildID : {build_id}")
    lines.append(" * This file is generated; do not edit by hand.")
    lines.append(" */")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <jni.h>")
    lines.append("")
    lines.append("/* Architecture identified from ELF header. */")
    lines.append(f"#define SO2C_TARGET_ARCH \"{arch}\"")
    lines.append("")
    return lines


def render_c_source_declarations(elf, exports, imports):
    lines = []
    lines.append("/*")
    lines.append(" * Generated by SO2C. Human-readable pseudo-C listing.")
    lines.append(" *")
    lines.append(" * The symbols below are the JNI entry-points (exports).")
    lines.append(" * Each body is a decompiled high-level reconstruction.")
    lines.append(" *")
    lines.append(" * NOTE: for stripped/unusual binaries symbol names may be")
    lines.append(" * reconstructed from ELF metadata only; bodies are "
                  "conservative.")
    lines.append(" */")
    lines.append("")
    return lines


def fmt_imports(imports):
    out = []
    for i in imports:
        out.append(f"    // import : {i.display}")
    return out


def render_startup(elf, imports, security):
    lines = []
    lines.append("")
    lines.append("/* ----------------------------------------------------------")
    lines.append(" * Dynamic linkage summary")
    lines.append(" * ---------------------------------------------------------- */")
    lines.append("")
    for imp in imports:
        lines.append(f"    // needs symbol : {imp.display}")
    lines.append("")
    return lines


def render_section_table(elf):
    lines = []
    lines.append("/* ----- ELF section layout ----- */")
    lines.append("    //   idx  name                addr          size")
    lines.append("    //   ---  ----                ----          ----")
    for s in elf.sections:
        lines.append("    //  {:>3}  {:<20} {:>10} {:>8}".format(
            s.index, s.name or ".none", hex(s.addr), hex(s.size)))
    lines.append("")
    return lines


def render_string_header():
    return ["/* ----- Referenced string constants ----- */", ""]


def render_security(security):
    lines = ["/* ----- PE/ELF hardening & metadata ----- */", ""]
    return lines